MyFirstASPNETWebApp/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPNETWebApp.Models
{
    public class CalculatorModel
    {
        [Required]
        [Range(0,100)]
        public string Assignments { get; set; }
        [Required]
        [Range(0, 100)]
        public string GroupProject { get; set; }
        [Required]
        [Range(0, 100)]
        public string Quizzes { get; set; }
        [Required]
        [Range(0, 100)]
        public string Exams { get; set; }
        [Required]
        [Range(0, 100)]
        public string Intex { get; set; }

    }
}

MyFirstASPNETWebApp/Controllers/aController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstASPNETWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPNETWebApp.Controllers
{
    public class aController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Calculator ()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Calculator(CalculatorModel model)
        {
            return View();
        }
    }
}

MyFirstASPNETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />
    <link rel="icon" href="~/img/bean-removebg-preview.png" />
</head>

<body>

    <nav>
        <a asp-controller="a" asp-action="Index">Home</a>
        <a asp-controller="a" asp-action="Calculator">Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    @*<footer>This is my footer.</footer>*@

    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
    <script src="~/js/calculator.js"></script>

</body>

</html>

MyFirstASPNETWebApp/Views/a/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CalculatorModel;

<h2>Grade Calculator: </h2>
<form method="post">
    <label>Assignments: </label>
    <input type="number" min="0" max="100" id="txtAssignments" asp-for="Assignments"/><br />
    <label>Group Project: </label>
    <input type="number" min="0" max="100" id="txtGroupProject" asp-for="GroupProject"/><br />
    <label>Quizzes: </label>
    <input type="number" min="0" max="100" id="txtQuizzes" asp-for="Quizzes"/><br />
    <label>Exams: </label>
    <input type="number" min="0" max="100" id="txtExams" asp-for="Exams"/><br />
    <label>INTEX: </label>
    <input type="number" min="0" max="100" id="txtIntex" asp-for="Intex"/><br />
    <input id="btnSend" type="submit" value="Calculate" />

    <div asp-validation-summary="All"></div>
</form>

MyFirstASPNETWebApp/Views/a/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Ransom Allphin";
}

<h1>Ransom Allphin</h1>
<img src="img/Boys-Track-Allphin.jpg" width="200" />

<p>There are a couple things that I would love to get out of this class. I would like to learn about the asp.net framework and it's features. I also want to know the basics of C# so that I am familiar with it if I need it later on in life. And the last thing is to 'sharp'en my skills in programming overall.</p>

<p>Top three jobs after graduating:</p>
<ul>
    <li>Data Analyst</li>
    <li>Something in Consulting</li>
    <li>Application Development</li>
</ul>